FROM rocker/r-ver:4.3.2

# -----------------------------
# System dependencies
# -----------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    # helpful tools
    # pkg-config \
    # shiny system dependencies
    zlib1g-dev \
    # devtools/remotes system dependencies
    libcurl4-openssl-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libssl-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libgit2-dev \
    # Seurat dependencies
    libglpk-dev \
    # hdf5r dependencies
    # patch \
    # BPCells dependencies
    libhdf5-dev \
  && rm -rf /var/lib/apt/lists/*
#     libudunits2-dev \
#     libgdal-dev \
#     libgeos-dev \
#     libproj-dev \
#     libfftw3-dev \
#     cmake \
#     build-essential \
#     && apt-get clean

# -----------------------------
# Install required R packages
# -----------------------------

# install shiny/UI packages
RUN R -e "options(warn=2); install.packages(c('shiny', 'shinyWidgets', 'colourpicker'))"

# Install devtools and remote for GitHub installs
RUN R -e "options(warn=2); install.packages(c('devtools', 'remotes'))"

# Install Seurat
RUN R -e "options(warn=2); install.packages('Seurat')"

# Install BPCells
RUN R -e "options(warn=2); remotes::install_github('bnprks/BPCells/r')"

# Install Seurat disk
# RUN R -e "options(warn=2); install.packages('hdf5r')"
# RUN R -e "options(warn=2); remotes::install_github('mojaveazure/seurat-disk')"

# CRAN first
# RUN R -e "install.packages(c( \
#     'Seurat', 'tidyverse', 'ggplot2', 'gridExtra',\
#     'harmony', 'NMF', 'circlize', 'msigdbr' \
# ))"


# Bioconductor packages
# RUN R -e "install.packages('BiocManager', repos='https://cloud.r-project.org')"

# RUN R -e "BiocManager::install(c( \
#   'Biobase','BiocGenerics','AnnotationDbi','org.Mm.eg.db', \
#   'monocle3', 'clusterProfiler','ComplexHeatmap' \
# ))"

# Monocle3 installation
# RUN R -e "BiocManager::install(c( \
#   'DelayedArray', 'DelayedMatrixStats', 'ggrastr', \
#   'limma', 'lme4', 'S4Vectors', 'SingleCellExperiment', \
#   'SummarizedExperiment', 'batchelor', 'HDF5Array', \
# ))"

# RUN R -e "remotes::install_github('bnprks/BPCells/r')"

# RUN R -e "devtools::install_github('cole-trapnell-lab/monocle3')"


# Install SeuratWrappers + CellChat (GitHub / Bioc)
# RUN R -e "remotes::install_github('satijalab/seurat-wrappers')"

# RUN R -e "devtools::install_github('sqjin/CellChat')"

# -----------------------------
# Copy Shiny app/set working dir
# -----------------------------
WORKDIR /app
COPY /app .

# -----------------------------
# Expose port & run
# -----------------------------
EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/app', host='0.0.0.0', port=3838)"]

# Broken packages:
    # Need BPCells?
    # SeuratWrappers
    # monocle3
    # CellChat
